name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  METAMASK_PRIVATE_KEY: ${{ secrets.METAMASK_PRIVATE_KEY }}
  MUMBAI_API_URL: ${{ secrets.MUMBAI_API_URL }}
  POLYGON_API_URL: ${{ secrets.POLYGON_API_URL }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn --ignore-scripts
        shell: bash
      # - name: Create local node and deploy
      #   run: |
      #     yarn hardhat node &
      #     yarn hardhat run scripts/deploy.js --network hardhat
      - name: Run Tests
        run: yarn hardhat test